#pragma once
#include <cstdint>
#include <Helpers/Networking/NetLibrary.hpp>

enum ServerCommands : MessageCommandType {
    SERVER_FRAGMENT = 0,
    SERVER_KEEP_ALIVE,
    SERVER_INITIAL_DATA,
    SERVER_MOVE_MOUSE,
    SERVER_PLACE_COMPONENT,
    SERVER_TRANSFORM_COMPONENT,
    SERVER_ERASE_COMPONENT,
    SERVER_UPDATE_COMPONENT,
    SERVER_RESOURCE_INIT,
    SERVER_RESOURCE_DATA,
    SERVER_CHAT_MESSAGE,
    SERVER_NEW_BOOKMARK,
    SERVER_REMOVE_BOOKMARK
};

enum ClientCommands : MessageCommandType {
    CLIENT_FRAGMENT = 0,
    CLIENT_KEEP_ALIVE,
    CLIENT_INITIAL_DATA,
    CLIENT_USER_CONNECT,
    CLIENT_USER_DISCONNECT,
    CLIENT_PLACE_COMPONENT,
    CLIENT_TRANSFORM_COMPONENT,
    CLIENT_ERASE_COMPONENT,
    CLIENT_UPDATE_COMPONENT,
    CLIENT_MOVE_MOUSE,
    CLIENT_NEW_RESOURCE,
    CLIENT_CHAT_MESSAGE,
    CLIENT_NEW_BOOKMARK,
    CLIENT_REMOVE_BOOKMARK
};

#define SAVEFILE_HEADER_LEN 12
#define SAVEFILE_HEADER "INFPNT000001"
