#pragma once
#include <cstdint>
#include <Helpers/Networking/NetLibrary.hpp>

enum ServerCommands : MessageCommandType {
    SERVER_FRAGMENT = 0,
    SERVER_KEEP_ALIVE,
    SERVER_INITIAL_DATA,
    SERVER_UPDATE_NETWORK_OBJECT,
    SERVER_UPDATE_MANY_NETWORK_OBJECTS,
    SERVER_NEW_RESOURCE_ID,
    SERVER_NEW_RESOURCE_DATA,
    SERVER_TRANSFORM_MANY_COMPONENTS
};

enum ClientCommands : MessageCommandType {
    CLIENT_FRAGMENT = 0,
    CLIENT_KEEP_ALIVE,
    CLIENT_INITIAL_DATA,
    CLIENT_UPDATE_NETWORK_OBJECT,
    CLIENT_UPDATE_MANY_NETWORK_OBJECTS,
    CLIENT_NEW_RESOURCE_ID,
    CLIENT_NEW_RESOURCE_DATA,
    CLIENT_TRANSFORM_MANY_COMPONENTS
};
